import FWCore.ParameterSet.Config as cms

TFileService = cms.Service("TFileService",
	fileName = cms.string('ntuple.root')
)

## ============  THE NTUPLIZER!!!  ===============
ntuplizer           = cms.EDAnalyzer("Ntuplizer",
    MonteCarlo      = cms.bool(False),
    UseFullName     = cms.bool(False),
    ## Monte Carlo only
#     GenFilterInfo   = cms.InputTag("genFilterEfficiencyProducer"),
#     GenRunInfo      = cms.InputTag("generator"),
#     GenEventInfo    = cms.InputTag("generator"),
#     PileupInfo      = cms.InputTag("addPileupInfo","","HLT"),
    ###################
    TriggerResults  = cms.VInputTag(cms.InputTag('TriggerResults','','HLT2')),
    TriggerPaths    = cms.vstring  (
                                  'HLT_ZeroBias_v',
                                  'HLT_L1SingleMu3_v',
                                  'HLT_L1SingleJet20_v',
                                  'HLT_Mu8_v',
                                  'HLT_CaloJet10_v',
                                  'HLT_PFJet20_v',
                                  'HLT_CaloJet10_BTagCSV0p30_PFJet20_v',
                                  'HLT_BTagMu_DiJet20_Mu5_v',
                                  'HLT_BTagMu_DiJet40_Mu5_v',
                                  'HLT_BTagMu_DiJet20_Mu5_BTagCSV0p30_L2L3Mu5_DiPFJet20_v',
                                  'HLT_DoubleJetsC100_DoubleBTagCSV_0p84_DoublePFJetsC100MaxDeta1p6_v',
                                  'HLT_CaloJets_Muons_CaloBTagCSV_PFJets_v',
               ),
    TriggerEvent  = cms.VInputTag(
                     cms.InputTag("hltTriggerSummaryAOD","","HLT2"),
                     ),
    TriggerObjectLabels    = cms.vstring  (
                                  'hltL1sZeroBias',
                                  'hltL1sSingleMu3',
                                  'hltL1fL1sMu3L1Filtered0',
                                  'hltL1sSingleJet20',
                                  'hltL1sSingleMu3IorSingleMu5IorSingleMu7',
                                  'hltL1fL1sMu5L1Filtered0',
                                  'hltL2fL1sMu5L1f0L2Filtered5',
                                  'hltL3fL1sMu5L1f0L2f5L3Filtered8',
                                  'hltL1sZeroBias',
                                  'hltSingleCaloJet10',
                                  'hltL1sZeroBias',
                                  'hltSingleCaloJet10',
                                  'hltSinglePFJet20',
                                  'hltL1sZeroBias',
                                  'hltSingleCaloBJet10',
                                  'hltBTagCaloCSV0p30WithMatching',
                                  'hltSinglePFBJet20',
                                  'hltL1sMu3JetC16dEtaMax0p4dPhiMax0p4',
                                  'hltBDiJet20L1FastJetCentral',
                                  'hltBSoftMuonDiJet20L1FastJetL25FilterByDR',
                                  'hltBSoftMuonDiJet20L1FastJetMu5L3FilterByDR',
                                  'hltL1sMu3JetC16dEtaMax0p4dPhiMax0p4',
                                  'hltBDiJet40L1FastJetCentral',
                                  'hltBSoftMuonDiJet40L1FastJetL25FilterByDR',
                                  'hltBSoftMuonDiJet40L1FastJetMu5L3FilterByDR',
                                  'hltL1sMu3JetC16dEtaMax0p4dPhiMax0p4',
                                  'hltL1fL1sMu5L1Filtered0',
                                  'hltBDiJet20L1FastJetCentral',
                                  'hltL2fL1sMu5L1f0L2Filtered5',
                                  'hltBSoftMuonDiJet20L1FastJetL25FilterByDR',
                                  'hltL3fL1sMu5L1f0L2f5L3Filtered5',
                                  'hltBSoftMuonDiJet20L1FastJetMu5L3FilterByDR',
                                  'hltBTagCaloCSV0p30WithMatching',
                                  'hltDoublePFBJet20',
                                  'hltL1sDoubleJetC100',
                                  'hltDoubleJetsC100',
                                  'hltBTagCaloCSVp014DoubleWithMatching',
                                  'hltDoublePFJetsC100',
                                  'hltDoublePFJetsC100MaxDeta1p6',
               ),
)
